### ISSUE TITLE
Fix tag versioning

### ISSUE THREAD

**Issue by puria** [ForkbombEu/ncr#95] opened 2024-03-11 15:33 UTC

**Comment by puria** [comment] 2024-05-31 13:45
Is this still an issue? @matteo-cristino in the last refactoring of actions, do you aligned the relase version with the build?

**Comment by matteo-cristino** [comment] 2024-05-31 14:33
I did, but this is still present. I think that the problem is that we have the version pushed with the new commit and since the ci is done on the prior commit, the new version is not there... But we use the same method for signroom, do we have correct version there or we are one back as here? 🤔

**Comment by matteo-cristino** [comment] 2024-05-31 17:08
I thought about a thing... maybe it can be resolved by simply using the actions/checkout with `fetch-depth: 0`. I will add the possiblity to set it in the dyne/pnpm action and will check if this solve the issue 🕵🏽

**Comment by matteo-cristino** [comment] 2024-06-04 08:44
Sadly `fetch-depth: 0` does not solve the issue 😢 will look for another solution

**Comment by puria** [comment] 2024-06-04 08:44
@matteo-cristino ok don't worry I'll take care

**Comment by matteo-cristino** [comment] 2024-06-04 12:38
Issue still present, I think it can be caused by the fact that we are doing the build before the release now

https://github.com/ForkbombEu/ncr/blob/ad1a606312072de6c662e46b5783fdb7cc738b26/.github/workflows/ci.yml#L44-L50

**Closed** 2024-06-04 14:10 UTC
